(define (problem turtlebot_example_task)
(:domain turtlebot_example)
(:objects
    fl0 fl1 - floor
    kinba - robot
    wp0-0 wp0-1 wp0-5 wp0-6 wp1-6 wp1-7 wp1-8  - waypoint
)
(:init
    (allowed_goto_waypoint )
    (current_elevator_waypoint wp0-6)
    (destination_waypoint wp1-8)
    (dock_at wp0-0)
    (elevator_access_waypoint wp0-5)
    (elevator_access_waypoint wp1-7)
    (elevator_waypoint wp0-6)
    (elevator_waypoint wp1-6)
    (greeting_waypoint wp0-1)
    (hallway_waypoint wp0-0)
    (hallway_waypoint wp0-1)
    (hallway_waypoint wp0-5)
    (hallway_waypoint wp1-7)
    (hallway_waypoint wp1-8)
    (outside_elevator kinba)
    (person_greeted )
    (person_guided )
    (robot_at kinba wp0-0)
    (undocked kinba)
    (waypoint_at_floor wp0-0 fl0)
    (waypoint_at_floor wp0-1 fl0)
    (waypoint_at_floor wp0-5 fl0)
    (waypoint_at_floor wp0-6 fl0)
    (waypoint_at_floor wp1-6 fl1)
    (waypoint_at_floor wp1-7 fl1)
    (waypoint_at_floor wp1-8 fl1)
)
(:goal (and
    (person_greeted kinba)
    (person_guided kinba)
    (docked kinba)
)))
